### ISSUE TITLE
use 0-flist instead of plain curl

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/action-publish#5]
Maybe we could refactor this action to be a more generic flist management tool featuring more use then just upload. 
Using https://github.com/threefoldtech/0-flist we could leverage all the feature of 0-flist inside a github action. 

That also automatically add new feature to this action as soon as they are implemented in 0-flist

**Comment by maxux** [comment]
Closing this, since we have https://github.com/threefoldtech/publish-flist now
